### PR TITLE
support the upcoming glob package

### PR DESCRIPTION
**Pull request by jakemac53**
Needs an override on the git branch for now, this is temporary for landing glob 2.0 internally as I will need to pull this in with the glob roll.

### CODE REVIEW

**Comment by srawlins** [comment]
Can you lay out the planned tasks here? Or comment on my guess, haha:

1. land this
2. import this into timezone internal
3. land glob in SDK DEPS, import it into internal
4. remove override in the timezone package?
5. `pub publish` the timezone package?

I'm fuzzy on how/when I publish with this nullsafety version of glob as a dep.

**Comment by jakemac53** [comment]
Your assumed plan was basically correct :)

> 1. land this
> 2. import this into timezone internal
> 3. land glob in SDK DEPS, import it into internal

4. Publish glob :)

> 4. remove override in the timezone package?
> 5. `pub publish` the timezone package?
> 
> I'm fuzzy on how/when I publish with this nullsafety version of glob as a dep.

You can publish at any time, once we have `2.12.0` stable we will publish a stable release, this is only a dev dependency anyways though.

**Comment by jakemac53** [comment]
Actually ya you probably have no reason to even bother with publishing since it is only a dev dep

**Comment by srawlins** [comment]
Thanks much!

**Pull request merged**
